app.py
from flask import Flask, Blueprint
from flask_login import LoginManager, login_required
from flask_sqlalchemy import SQLAlchemy
import os
from routes.admin_dashboard_routes import dashboard_route
from routes.admin_manage_coaches_routes import edit_coaches_route, manage_coaches_route, delete_coach_route
from routes.admin_manage_memberships_routes import manage_memberships_route, edit_membership_route, delete_membership_route
from routes.auth_routes import login_route, register_route
from routes.user_routes import home_route, memberships_route, coaches_route, payments_route, logout_route
from services.Config import Config
from services.data_obtainer import load_user_data

app = Flask(__name__)
app.config.from_object(Config)
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
db = SQLAlchemy()
db.init_app(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'login'


admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/', methods=['GET'])
def dashboard():
    return dashboard_route(db, app)

@admin_bp.route('/manage-memberships', methods=['GET', 'POST'])
def manage_memberships():
    return manage_memberships_route(db, app)


@admin_bp.route('/edit-membership/<membership_id>', methods=['GET', 'POST'])
def edit_membership(membership_id):
    return edit_membership_route(membership_id, db, app)


@admin_bp.route('/delete-membership/<uuid:membership_id>', methods=['GET','POST'])
def delete_membership(membership_id):
    return delete_membership_route(membership_id, db, app)


@admin_bp.route('/manage-coaches', methods=['GET', 'POST'])
def manage_coaches():
    return manage_coaches_route(db, app)


@admin_bp.route('/edit-coach/<coach_id>', methods=['GET', 'POST'])
def edit_coach(coach_id):
    return edit_coaches_route(coach_id, db, app)

@admin_bp.route('/delete-coach/<coach_id>', methods=['GET', 'POST'])
def delete_coach(coach_id):
    return delete_coach_route(coach_id, db, app)

app.register_blueprint(admin_bp, url_prefix='/admin')

@login_manager.user_loader
def load_user(member_id):
    return load_user_data(member_id, db)

@app.route('/login', methods=['GET', 'POST'])
def login():
    return login_route(db)

@app.route('/register', methods=['GET', 'POST'])
def register():
    return register_route(db)

@app.route('/', methods=['GET','POST'])
@login_required
def home():
    return home_route(db)


@app.route('/memberships', methods=['GET', 'POST'])
@login_required
def memberships():
    return memberships_route(db)

@app.route('/coaches')
@login_required
def coaches():
    return coaches_route(db)

@app.route('/payments', methods=['GET', 'POST'])
@login_required
def payments():
    return payments_route(db)

@app.route('/logout')
@login_required
def logout():
    return logout_route()

if __name__ == '__main__':
    app.run(debug=True)

templates/admin_home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
{% include 'includes/admin_navbar.html' %}

<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6 col-md-12 mb-4">
            <img src="{{ url_for('static', filename='img/ActiveMembershipCounts.png') }}" class="img-fluid" alt="Active Membership Counts">
        </div>
        <div class="col-lg-6 col-md-12 mb-4">
            <img src="{{ url_for('static', filename='img/MonthlyRevenue.png') }}" class="img-fluid" alt="Monthly Revenue">
        </div>
        <div class="col-lg-6 col-md-12 mb-4">
            <img src="{{ url_for('static', filename='img/ActiveMemberCoachStatus.png') }}" class="img-fluid" alt="Active Members by Coach Status">
        </div>
        <div class="col-lg-6 col-md-12 mb-4">
            <img src="{{ url_for('static', filename='img/PaymentTypeCounts.png') }}" class="img-fluid" alt="Payment Type Counts">
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/coaches.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <title>Trainers</title>
</head>
<body>
    {% include 'includes/navbar.html' %}

    <div class="container mt-4">
        <div class="text-center mb-4">
            <h1>Тренери</h1>
        </div>
        <div class="row g-4">
            {% for coach in coaches %}
                <div class="col-lg-3 col-md-4 col-sm-6 d-flex justify-content-center">
                    <div class="card" style="width: 18rem;">
                        <img src="./static/img/{{ coach['photo'] }}" class="card-img-top" alt="{{ coach['fullname'] }}" height="300">
                        <div class="card-body d-flex flex-column justify-content-between">
                            <h5 class="card-title">{{ coach['fullname'] }}</h5>
                            <p class="card-text">{{ coach['speciality'] }}</p>
                            <p class="card-text">Номер телефону: {{ coach['phonenumber'] }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/edit_coach.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Coach</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h2>Редагувати тренера</h2>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control", value=coach['name']) }}
        </div>

        <div class="mb-3">
            {{ form.lastName.label(class="form-label") }}
            {{ form.lastName(class="form-control", value=coach['lastName']) }}
        </div>

        <div class="mb-3">
            {{ form.speciality.label(class="form-label") }}
            {{ form.speciality(class="form-control", value=coach['speciality']) }}
        </div>

        <div class="mb-3">
            {{ form.phoneNumber.label(class="form-label") }}
            {{ form.phoneNumber(class="form-control", value=coach['phoneNumber']) }}
        </div>

        <div class="mb-3">
            {{ form.photo.label(class="form-label") }}
            {{ form.photo(class="form-control") }}
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Редагувати</button>
        </div>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/edit_membership.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Membership</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h2>Редагувати абонемент</h2>
    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="mb-3">
            <label for="type" class="form-label">{{ form.type.label }}</label>
            {{ form.type(class="form-control", value=membership['type']) }}
        </div>

        <div class="mb-3">
            <label for="price" class="form-label">{{ form.price.label }}</label>
            {{ form.price(class="form-control", value=membership['price']) }}
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">{{ form.description.label }}</label>
            {{ form.description(class="form-control", value=membership['description']) }}
        </div>

        <div class="mb-3 form-check">
            <label class="form-check-label">
                {% if membership['hascoach'] %}
                    {{ form.hascoach(checked=True) }} З тренером
                {% else %}
                    {{ form.hascoach() }} З тренером
                {% endif %}
            </label>
        </div>

        <button type="submit" class="btn btn-primary">Редагувати</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <title>Домашня</title>
</head>
<body>
    {% include 'includes/navbar.html' %}
    <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center mb-4">
                        <h1>Вітання, {{ current_user.name }} {{ current_user.surname }}!</h1>
                    </div>

                    <div class="card shadow-lg">
                        <div class="card-header bg-primary text-white text-center">
                            <h4>Користувацька інформація</h4>
                        </div>
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><strong>Тип абонементу:</strong> {{ current_user.membership_type or 'Немає інформації'}}</li>
                                <li class="list-group-item">
                                    <strong>Дата закінчення абонементу:</strong>
                                    {% if current_user.membership_end_date %}
                                        {{ current_user.membership_end_date.strftime('%Y-%m-%d %H:%M:%S') }}
                                    {% else %}
                                        Немає інформації
                                    {% endif %}
                                </li>
                                <li class="list-group-item"><strong>Тренер:</strong> {{ current_user.coach_full_name or 'Без тренера' }}</li>
                                <li class="list-group-item"><strong>Баланс:</strong> {{ "%.2f"|format(current_user.balance) }} грн</li>
                            </ul>
                        <div class="text-center mt-4">
                            <button class="btn btn-secondary" id="btn_changePassword">Змінити пароль</button>
                            <button class="btn btn-primary" id="btn_deposit">Поповнити баланс</button>
                        </div>
                        </div>
                    </div>

                    <div class="text-center mt-4">
                        <a href="{{ url_for('logout') }}" class="btn btn-danger">Logout</a>
                    </div>
                </div>
            </div>
    </div>

    <div class="modal fade" id="depositModal" tabindex="-1" aria-labelledby="depositModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="depositModalLabel">Поповнення балансу</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST">
                        {{ deposit_from.hidden_tag() }}
                        <div class="mb-3">
                            {{ deposit_from.payment_type.label(class_="form-label") }}
                            {{ deposit_from.payment_type(class_="form-select") }}
                        </div>
                        <div class="mb-3">
                            {{ deposit_from.amount.label(class_="form-label") }}
                            {{ deposit_from.amount(class_="form-control") }}
                        </div>
                        <button type="submit" class="btn btn-primary">
                            {{ deposit_from.submit.label.text }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="changePasswordModal" tabindex="-1" aria-labelledby="changePasswordModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="changePasswordModalLabel">Змінити пароль</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST">
                        {{ password_form.hidden_tag() }}
                        <div class="mb-3">
                            {{ password_form.old_password.label(class_="form-label") }}
                            {{ password_form.old_password(class_="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ password_form.new_password.label(class_="form-label") }}
                            {{ password_form.new_password(class_="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ password_form.confirm_password.label(class_="form-label") }}
                            {{ password_form.confirm_password(class_="form-control") }}
                        </div>
                        <button type="submit" class="btn btn-primary">{{ password_form.submit.label }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="toast-container position-fixed top-0 end-0 p-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="toast align-items-center border-0 mb-2" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="d-flex alert alert-{{ category }}">
                            <div class="toast-body">
                                {{ message }}
                            </div>
                            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../static/toast.js"></script>
    <script src="../static/home_modals.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <title>Login</title>
</head>
<body>
    <div class="container mt-5">
        <h1>Авторизація</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.phoneNumber.label(class_="form-label") }}
                {{ form.phoneNumber(class_="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.password.label(class_="form-label") }}
                {{ form.password(class_="form-control") }}
            </div>
            {% if form.error_message %}
            <div style="color: red;">
                {{ form.error_message }}
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary">{{ form.submit.label }}</button>
        </form>
        <p class="m-2">або</p>
        <a href="/register"><button class="btn btn-primary">Реєстрація</button></a>
    </div>
</body>
</html>

templates/manage_coaches.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Coach</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'includes/admin_navbar.html' %}
<div class="container mt-5">
    <h2>Додати тренера</h2>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addCoachModal">
      Додати тренера
    </button>

    <div class="modal fade" id="addCoachModal" tabindex="-1" aria-labelledby="addCoachModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addCoachModalLabel">Додати тренера</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="POST" enctype="multipart/form-data" action="{{ url_for('admin.manage_coaches') }}">
                {{ form.hidden_tag() }}
              <div class="mb-3">
                <label for="name" class="form-label">{{ form.name.label }}</label>
                {{ form.name(class="form-control") }}
              </div>

              <div class="mb-3">
                <label for="lastName" class="form-label">{{ form.lastName.label }}</label>
                {{ form.lastName(class="form-control") }}
              </div>

              <div class="mb-3">
                <label for="speciality" class="form-label">{{ form.speciality.label }}</label>
                {{ form.speciality(class="form-control") }}
              </div>

              <div class="mb-3">
                <label for="phoneNumber" class="form-label">{{ form.phoneNumber.label }}</label>
                {{ form.phoneNumber(class="form-control") }}
                {% for error in form.phoneNumber.errors %}
                  <div class="text-danger">{{ error }}</div>
                {% endfor %}
              </div>

              <div class="mb-3">
                <label for="photo" class="form-label">{{ form.photo.label }}</label>
                {{ form.photo(class="form-control") }}
              </div>

              <button type="submit" class="btn btn-primary">Додати</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div class="text-center mb-4">
            <h1>Тренери</h1>
        </div>
        <div class="row g-4">
            {% for coach in coaches %}
                <div class="col-lg-3 col-md-4 col-sm-6 d-flex justify-content-center">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ url_for('static', filename='img/' + (coach['photo'] or 'person.png')) }}" class="card-img-top" alt="{{ coach['fullname'] }}" height="300">
                        <div class="card-body d-flex flex-column justify-content-between">
                            <h5 class="card-title">{{ coach['fullname'] }}</h5>
                            <p class="card-text">{{ coach['speciality'] }}</p>
                            <p class="card-text">Номер телефону: {{ coach['phonenumber'] }}</p>
                            <div class="d-flex justify-content-between">
                                <a href="{{ url_for('admin.edit_coach', coach_id=coach['coachid']) }}" class="btn btn-warning btn-sm">Редагувати</a>
                                <form method="POST" action="{{ url_for('admin.delete_coach', coach_id=coach['coachid']) }}">
                                    <button type="submit" class="btn btn-danger btn-sm">Видалити</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/manage_membership.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Membership</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'includes/admin_navbar.html' %}
<div class="container mt-5">
    <h2>Додати абонемент</h2>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addMembershipModal">Додати абонемент</button>

<div class="modal fade" id="addMembershipModal" tabindex="-1" aria-labelledby="addMembershipModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addMembershipModalLabel">Додати абонемент</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="{{ url_for('admin.manage_memberships') }}">
          {{ form.hidden_tag() }}
          <div class="mb-3">
            <label for="type" class="form-label">{{ form.type.label }}</label>
            {{ form.type(class="form-control") }}
          </div>
          <div class="mb-3">
            <label for="price" class="form-label">{{ form.price.label }}</label>
            {{ form.price(class="form-control") }}
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">{{ form.description.label }}</label>
            {{ form.description(class="form-control") }}
          </div>
          <div class="mb-3 form-check">
            <label class="form-check-label">
              {{ form.hascoach() }} З тренером
            </label>
          </div>
          <button type="submit" class="btn btn-primary">Додати</button>
        </form>
      </div>
    </div>
  </div>
</div>

    <h3 class="mt-5">Абонементи</h3>
    <table class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>Тип</th>
                <th>Ціна</th>
                <th>Опис</th>
                <th>Дія</th>
            </tr>
        </thead>
        <tbody>
            {% for membership in memberships %}
            <tr>
                <td>{{ membership.type }}</td>
                <td>{{ membership.price }}</td>
                <td>{{ membership.description }}</td>
                <td>
                    <a href="{{ url_for('admin.edit_membership', membership_id=membership['membershipid']) }}" class="btn btn-warning btn-sm">Редагувати</a>
                    <a href="{{ url_for('admin.delete_membership', membership_id=membership['membershipid']) }}" class="btn btn-danger btn-sm">Видалити</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/memberships.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <title>Абонементи</title>
</head>
<body>
    {% include 'includes/navbar.html' %}
    <div class="container mt-4">
        <div class="text-center mb-4">
            <h1>Абонементи</h1>
        </div>
        <div class="row g-4">
            {% for membership in memberships %}
                <div class="col-lg-3 col-md-4 col-sm-6 d-flex justify-content-center">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body d-flex flex-column justify-content-between">
                            <h5 class="card-title">{{ membership.type }}</h5>
                            <form method="POST" action="{{ url_for('memberships') }}">
                                {{ form.hidden_tag() }}
                                <input type="hidden" name="membership_id" value="{{ membership.membershipid }}">

                                <h6 class="card-subtitle mb-2 text-muted">Ціна {{ membership.price }} грн на місяць</h6>
                                <p class="card-text">{{ membership.description }}</p>

                                {% if membership.hascoach %}
                                    <div class="mb-3">
                                        {{ form.picked_coach.label(class="form-label") }}
                                        {{ form.picked_coach(class="form-select") }}
                                    </div>
                                {% endif %}

                                {% if membership['membershipid'] == membership_ids %}
                                    <button type="submit" class="btn btn-primary" disabled>
                                        {{ form.submit.label.text }}
                                    </button>
                                {% else %}
                                    <button type="submit" class="btn btn-primary">
                                        {{ form.submit.label.text }}
                                    </button>
                                {% endif %}
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="toast-container position-fixed top-0 end-0 p-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="toast align-items-center border-0 mb-2" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="d-flex alert alert-{{ category }}">
                            <div class="toast-body">
                                {{ message }}
                            </div>
                            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../static/toast.js"></script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container mt-5">
    <h2 class="text-center">Реєстрація</h2>
    <form method="POST" action="{{ url_for('register') }}">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {{ form.name(class="form-control") }}
            {% for error in form.name.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{ form.last_name.label(class="form-label") }}
            {{ form.last_name(class="form-control") }}
            {% for error in form.last_name.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{ form.phone_number.label(class="form-label") }}
            {{ form.phone_number(class="form-control") }}
            {% for error in form.phone_number.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{ form.password.label(class="form-label") }}
            {{ form.password(class="form-control") }}
            {% for error in form.password.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="mb-3">
            {{ form.confirm_password.label(class="form-label") }}
            {{ form.confirm_password(class="form-control") }}
            {% for error in form.confirm_password.errors %}
                <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
</body>
</html>